<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-35ASNQI8" ignored="0" name="t2" tests="3" failures="2" timestamp="2020-11-16T08:53:45 CST" time="6.068" errors="0">
  <testcase name="test2" time="0.005" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.testCases.LoginTest.test2(LoginTest.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.testCases.LoginTest.test3(LoginTest.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="com.webtest.testCases.LoginTest"/>
</testsuite> <!-- t2 -->
